version: '3'
services:
  nwabap:
    image: nwabap
    hostname: vhcalnplci
    ports:
      - "5000:5000"
      - "3200:3200"
      - "3300:3300"
      - "8000:8000"
      - "44300:44300"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    container_name: myabap
